tasks:
  - name: Gitbook
    before: cd ./gitbook
    init: npm install
    command: npm run book
    openIn: right
  - name: Main UI
    init: npm install
    command: npm run boot
    openIn: right
    openMode: tab-after

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.1:DO6k4GCpqhwZcKo+jY9xjQ==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
    - mikestead.dotenv@1.0.1:SSXjr5hZcbqSF7nMIhTNnA==
    - wayou.vscode-todo-highlight@1.0.4:8IqxuxCVol2WnScJc5xVzg==

ports:
  - port: 4000
    onOpen: ignore
  - port: 35729
    onOpen: ignore
